# Generated by Django 5.2.5 on 2025-08-20 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_doctor_patientdoctormapping_auditlog_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='patientdoctormapping',
            name='unique_patient_doctor',
        ),
        migrations.AddConstraint(
            model_name='patientdoctormapping',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('patient', 'doctor'), name='unique_active_patient_doctor'),
        ),
    ]
